<!doctype html>
<html>
  <head>
    <title>API Zoox Challenge</title>
    <style type="text/css">
      body {
      	font-family: Trebuchet MS, sans-serif;
      	font-size: 15px;
      	color: #444;
      	margin-right: 24px;
      }

      h1	{
      	font-size: 25px;
      }
      h2	{
      	font-size: 20px;
      }
      h3	{
      	font-size: 16px;
      	font-weight: bold;
      }
      hr	{
      	height: 1px;
      	border: 0;
      	color: #ddd;
      	background-color: #ddd;
      }

      .app-desc {
        clear: both;
        margin-left: 20px;
      }
      .param-name {
        width: 100%;
      }
      .license-info {
        margin-left: 20px;
      }

      .license-url {
        margin-left: 20px;
      }

      .model {
        margin: 0 0 0px 20px;
      }

      .method {
        margin-left: 20px;
      }

      .method-notes	{
      	margin: 10px 0 20px 0;
      	font-size: 90%;
      	color: #555;
      }

      pre {
        padding: 10px;
        margin-bottom: 2px;
      }

      .http-method {
       text-transform: uppercase;
      }

      pre.get {
        background-color: #0f6ab4;
      }

      pre.post {
        background-color: #10a54a;
      }

      pre.put {
        background-color: #c5862b;
      }

      pre.delete {
        background-color: #a41e22;
      }

      .huge	{
      	color: #fff;
      }

      pre.example {
        background-color: #f3f3f3;
        padding: 10px;
        border: 1px solid #ddd;
      }

      code {
        white-space: pre;
      }

      .nickname {
        font-weight: bold;
      }

      .method-path {
        font-size: 1.5em;
        background-color: #0f6ab4;
      }

      .up {
        float:right;
      }

      .parameter {
        width: 500px;
      }

      .param {
        width: 500px;
        padding: 10px 0 0 20px;
        font-weight: bold;
      }

      .param-desc {
        width: 700px;
        padding: 0 0 0 20px;
        color: #777;
      }

      .param-type {
        font-style: italic;
      }

      .param-enum-header {
      width: 700px;
      padding: 0 0 0 60px;
      color: #777;
      font-weight: bold;
      }

      .param-enum {
      width: 700px;
      padding: 0 0 0 80px;
      color: #777;
      font-style: italic;
      }

      .field-label {
        padding: 0;
        margin: 0;
        clear: both;
      }

      .field-items	{
      	padding: 0 0 15px 0;
      	margin-bottom: 15px;
      }

      .return-type {
        clear: both;
        padding-bottom: 10px;
      }

      .param-header {
        font-weight: bold;
      }

      .method-tags {
        text-align: right;
      }

      .method-tag {
        background: none repeat scroll 0% 0% #24A600;
        border-radius: 3px;
        padding: 2px 10px;
        margin: 2px;
        color: #FFF;
        display: inline-block;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
  <h1>API Zoox Challenge</h1>
    <div class="app-desc">API Region City and State</div>
    <div class="app-desc">Contact Info: <a href="rafael.harus@gmail.com">rafael.harus@gmail.com</a></div>
    <div class="app-desc">Version: 1.0.0</div>

    <div class="license-info">All rights reserved</div>
    <div class="license-url">http://apache.org/licenses/LICENSE-2.0.html</div>
  <h2>Access</h2>
    <ol>
      <li>APIKey KeyParamName:X-Api-Key KeyInQuery:false KeyInHeader:true</li>
    </ol>

  <h2><a name="__Methods">Methods</a></h2>
  [ Jump to <a href="#__Models">Models</a> ]

  <h3>Table of Contents </h3>
  <div class="method-summary"></div>
  <h4><a href="#City">City</a></h4>
  <ul>
  <li><a href="#v1CityGet"><code><span class="http-method">get</span> /v1/city</code></a></li>
  <li><a href="#v1CityIdDelete"><code><span class="http-method">delete</span> /v1/city/{id}</code></a></li>
  <li><a href="#v1CityIdPut"><code><span class="http-method">put</span> /v1/city/{id}</code></a></li>
  <li><a href="#v1CityPost"><code><span class="http-method">post</span> /v1/city</code></a></li>
  </ul>
  <h4><a href="#State">State</a></h4>
  <ul>
  <li><a href="#v1StateGet"><code><span class="http-method">get</span> /v1/state</code></a></li>
  <li><a href="#v1StateIdDelete"><code><span class="http-method">delete</span> /v1/state/{id}</code></a></li>
  <li><a href="#v1StateIdPut"><code><span class="http-method">put</span> /v1/state/{id}</code></a></li>
  <li><a href="#v1StatePost"><code><span class="http-method">post</span> /v1/state</code></a></li>
  </ul>

  <h1><a name="City">City</a></h1>
  <div class="method"><a name="v1CityGet"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /v1/city</code></pre></div>
    <div class="method-summary">City Collection (<span class="nickname">v1CityGet</span>)</div>
    <div class="method-notes"></div>







    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#CollectionCity">CollectionCity</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "_page" : 6,
  "_total_items" : 0,
  "_links" : {
    "self" : {
      "href" : "http://{{host}}/v1/state?page=1"
    }
  },
  "_embedded" : {
    "states" : [ {
      "createdAt" : "2020-06-30T10:00:00-03:00",
      "deletedAt" : "2020-06-30T10:00:00-03:00",
      "deleted" : false,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/v1/city/90f10584-6260-4d99-a23d-f521934b865f"
        }
      },
      "stateId" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
      "name" : "Rio de Janeiro",
      "id" : "90f10584-6260-4d99-a23d-f521934b865f",
      "updatedAt" : "2020-06-30T10:00:00-03:00"
    }, {
      "createdAt" : "2020-06-30T10:00:00-03:00",
      "deletedAt" : "2020-06-30T10:00:00-03:00",
      "deleted" : false,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/v1/city/90f10584-6260-4d99-a23d-f521934b865f"
        }
      },
      "stateId" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
      "name" : "Rio de Janeiro",
      "id" : "90f10584-6260-4d99-a23d-f521934b865f",
      "updatedAt" : "2020-06-30T10:00:00-03:00"
    } ]
  },
  "_page_count" : 1
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    OK
        <a href="#CollectionCity">CollectionCity</a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="v1CityIdDelete"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /v1/city/{id}</code></pre></div>
    <div class="method-summary">Delete a city (<span class="nickname">v1CityIdDelete</span>)</div>
    <div class="method-notes"></div>

    <h3 class="field-label">Path parameters</h3>
    <div class="field-items">
      <div class="param">id (required)</div>

            <div class="param-desc"><span class="param-type">Path Parameter</span> &mdash; city id format: uuid</div>    </div>  <!-- field-items -->






    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#City">City</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "createdAt" : "2020-06-30T10:00:00-03:00",
  "deletedAt" : "2020-06-30T10:00:00-03:00",
  "deleted" : false,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/v1/city/90f10584-6260-4d99-a23d-f521934b865f"
    }
  },
  "stateId" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
  "name" : "Rio de Janeiro",
  "id" : "90f10584-6260-4d99-a23d-f521934b865f",
  "updatedAt" : "2020-06-30T10:00:00-03:00"
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    OK
        <a href="#City">City</a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="v1CityIdPut"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /v1/city/{id}</code></pre></div>
    <div class="method-summary">Update a city (<span class="nickname">v1CityIdPut</span>)</div>
    <div class="method-notes"></div>

    <h3 class="field-label">Path parameters</h3>
    <div class="field-items">
      <div class="param">id (required)</div>

            <div class="param-desc"><span class="param-type">Path Parameter</span> &mdash; city id format: uuid</div>    </div>  <!-- field-items -->

    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">body <a href="#body_3">body_3</a> (optional)</div>

            <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash; city body </div>
                </div>  <!-- field-items -->




    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#City">City</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "createdAt" : "2020-06-30T10:00:00-03:00",
  "deletedAt" : "2020-06-30T10:00:00-03:00",
  "deleted" : false,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/v1/city/90f10584-6260-4d99-a23d-f521934b865f"
    }
  },
  "stateId" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
  "name" : "Rio de Janeiro",
  "id" : "90f10584-6260-4d99-a23d-f521934b865f",
  "updatedAt" : "2020-06-30T10:00:00-03:00"
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    OK
        <a href="#City">City</a>
    <h4 class="field-label">422</h4>
    Unprocessable Entity
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="v1CityPost"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /v1/city</code></pre></div>
    <div class="method-summary">Create a city (<span class="nickname">v1CityPost</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">body <a href="#body_2">body_2</a> (optional)</div>

            <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash; city body </div>
                </div>  <!-- field-items -->




    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#City">City</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "createdAt" : "2020-06-30T10:00:00-03:00",
  "deletedAt" : "2020-06-30T10:00:00-03:00",
  "deleted" : false,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/v1/city/90f10584-6260-4d99-a23d-f521934b865f"
    }
  },
  "stateId" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
  "name" : "Rio de Janeiro",
  "id" : "90f10584-6260-4d99-a23d-f521934b865f",
  "updatedAt" : "2020-06-30T10:00:00-03:00"
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">201</h4>
    OK
        <a href="#City">City</a>
    <h4 class="field-label">422</h4>
    Unprocessable Entity
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <h1><a name="State">State</a></h1>
  <div class="method"><a name="v1StateGet"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="get"><code class="huge"><span class="http-method">get</span> /v1/state</code></pre></div>
    <div class="method-summary">State Collection (<span class="nickname">v1StateGet</span>)</div>
    <div class="method-notes"></div>







    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#CollectionState">CollectionState</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "_page" : 6,
  "_total_items" : 0,
  "_links" : {
    "self" : {
      "href" : "http://{{host}}/v1/state?page=1"
    }
  },
  "_embedded" : {
    "states" : [ {
      "createdAt" : "2020-06-30T10:00:00-03:00",
      "deletedAt" : "2020-06-30T10:00:00-03:00",
      "deleted" : false,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/v1/state/90f0fd07-f3c4-42a1-84fe-b29fa1af04da"
        }
      },
      "name" : "Rio de Janeiro",
      "id" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
      "shortName" : "RJ",
      "updatedAt" : "2020-06-30T10:00:00-03:00"
    }, {
      "createdAt" : "2020-06-30T10:00:00-03:00",
      "deletedAt" : "2020-06-30T10:00:00-03:00",
      "deleted" : false,
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/v1/state/90f0fd07-f3c4-42a1-84fe-b29fa1af04da"
        }
      },
      "name" : "Rio de Janeiro",
      "id" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
      "shortName" : "RJ",
      "updatedAt" : "2020-06-30T10:00:00-03:00"
    } ]
  },
  "_page_count" : 1
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    OK
        <a href="#CollectionState">CollectionState</a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="v1StateIdDelete"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="delete"><code class="huge"><span class="http-method">delete</span> /v1/state/{id}</code></pre></div>
    <div class="method-summary">Deleted a state (<span class="nickname">v1StateIdDelete</span>)</div>
    <div class="method-notes"></div>

    <h3 class="field-label">Path parameters</h3>
    <div class="field-items">
      <div class="param">id (required)</div>

            <div class="param-desc"><span class="param-type">Path Parameter</span> &mdash; state id format: uuid</div>    </div>  <!-- field-items -->






    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#State">State</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "createdAt" : "2020-06-30T10:00:00-03:00",
  "deletedAt" : "2020-06-30T10:00:00-03:00",
  "deleted" : false,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/v1/state/90f0fd07-f3c4-42a1-84fe-b29fa1af04da"
    }
  },
  "name" : "Rio de Janeiro",
  "id" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
  "shortName" : "RJ",
  "updatedAt" : "2020-06-30T10:00:00-03:00"
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    OK
        <a href="#State">State</a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="v1StateIdPut"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="put"><code class="huge"><span class="http-method">put</span> /v1/state/{id}</code></pre></div>
    <div class="method-summary">Update a state (<span class="nickname">v1StateIdPut</span>)</div>
    <div class="method-notes"></div>

    <h3 class="field-label">Path parameters</h3>
    <div class="field-items">
      <div class="param">id (required)</div>

            <div class="param-desc"><span class="param-type">Path Parameter</span> &mdash; state id format: uuid</div>    </div>  <!-- field-items -->

    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">body <a href="#body_1">body_1</a> (optional)</div>

            <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash; state body </div>
                </div>  <!-- field-items -->




    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#State">State</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "createdAt" : "2020-06-30T10:00:00-03:00",
  "deletedAt" : "2020-06-30T10:00:00-03:00",
  "deleted" : false,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/v1/state/90f0fd07-f3c4-42a1-84fe-b29fa1af04da"
    }
  },
  "name" : "Rio de Janeiro",
  "id" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
  "shortName" : "RJ",
  "updatedAt" : "2020-06-30T10:00:00-03:00"
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">200</h4>
    OK
        <a href="#State">State</a>
    <h4 class="field-label">422</h4>
    Unprocessable Entity
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>
  <div class="method"><a name="v1StatePost"></a>
    <div class="method-path">
    <a class="up" href="#__Methods">Up</a>
    <pre class="post"><code class="huge"><span class="http-method">post</span> /v1/state</code></pre></div>
    <div class="method-summary">Create a state (<span class="nickname">v1StatePost</span>)</div>
    <div class="method-notes"></div>


    <h3 class="field-label">Consumes</h3>
    This API call consumes the following media types via the <span class="header">Content-Type</span> request header:
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Request body</h3>
    <div class="field-items">
      <div class="param">body <a href="#body">body</a> (optional)</div>

            <div class="param-desc"><span class="param-type">Body Parameter</span> &mdash; state body </div>
                </div>  <!-- field-items -->




    <h3 class="field-label">Return type</h3>
    <div class="return-type">
      <a href="#State">State</a>

    </div>

    <!--Todo: process Response Object and its headers, schema, examples -->

    <h3 class="field-label">Example data</h3>
    <div class="example-data-content-type">Content-Type: application/json</div>
    <pre class="example"><code>{
  "createdAt" : "2020-06-30T10:00:00-03:00",
  "deletedAt" : "2020-06-30T10:00:00-03:00",
  "deleted" : false,
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/v1/state/90f0fd07-f3c4-42a1-84fe-b29fa1af04da"
    }
  },
  "name" : "Rio de Janeiro",
  "id" : "90f0fd07-f3c4-42a1-84fe-b29fa1af04da",
  "shortName" : "RJ",
  "updatedAt" : "2020-06-30T10:00:00-03:00"
}</code></pre>

    <h3 class="field-label">Produces</h3>
    This API call produces the following media types according to the <span class="header">Accept</span> request header;
    the media type will be conveyed by the <span class="header">Content-Type</span> response header.
    <ul>
      <li><code>application/json</code></li>
    </ul>

    <h3 class="field-label">Responses</h3>
    <h4 class="field-label">201</h4>
    Created OK
        <a href="#State">State</a>
    <h4 class="field-label">422</h4>
    Unprocessable Entity
        <a href="#"></a>
  </div> <!-- method -->
  <hr/>

  <h2><a name="__Models">Models</a></h2>
  [ Jump to <a href="#__Methods">Methods</a> ]

  <h3>Table of Contents</h3>
  <ol>
    <li><a href="#City"><code>City</code></a></li>
    <li><a href="#City__links"><code>City__links</code></a></li>
    <li><a href="#City__links_self"><code>City__links_self</code></a></li>
    <li><a href="#CollectionCity"><code>CollectionCity</code></a></li>
    <li><a href="#CollectionCity__embedded"><code>CollectionCity__embedded</code></a></li>
    <li><a href="#CollectionState"><code>CollectionState</code></a></li>
    <li><a href="#CollectionState__embedded"><code>CollectionState__embedded</code></a></li>
    <li><a href="#CollectionState__links"><code>CollectionState__links</code></a></li>
    <li><a href="#CollectionState__links_self"><code>CollectionState__links_self</code></a></li>
    <li><a href="#State"><code>State</code></a></li>
    <li><a href="#State__links"><code>State__links</code></a></li>
    <li><a href="#State__links_self"><code>State__links_self</code></a></li>
    <li><a href="#body"><code>body</code></a></li>
    <li><a href="#body_1"><code>body_1</code></a></li>
    <li><a href="#body_2"><code>body_2</code></a></li>
    <li><a href="#body_3"><code>body_3</code></a></li>
  </ol>

  <div class="model">
    <h3><a name="City"><code>City</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">id (optional)</div><div class="param-desc"><span class="param-type"><a href="#UUID">UUID</a></span>  format: uuid</div>
          <div class="param-desc"><span class="param-type">example: 90f10584-6260-4d99-a23d-f521934b865f</span></div>
<div class="param">name (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  format: string</div>
          <div class="param-desc"><span class="param-type">example: Rio de Janeiro</span></div>
<div class="param">stateId (optional)</div><div class="param-desc"><span class="param-type"><a href="#UUID">UUID</a></span>  format: uuid</div>
          <div class="param-desc"><span class="param-type">example: 90f0fd07-f3c4-42a1-84fe-b29fa1af04da</span></div>
<div class="param">createdAt (optional)</div><div class="param-desc"><span class="param-type"><a href="#DateTime">Date</a></span>  format: date-time</div>
          <div class="param-desc"><span class="param-type">example: 2020-06-30T10:00-03:00</span></div>
<div class="param">updatedAt (optional)</div><div class="param-desc"><span class="param-type"><a href="#DateTime">Date</a></span>  format: date-time</div>
          <div class="param-desc"><span class="param-type">example: 2020-06-30T10:00-03:00</span></div>
<div class="param">deleted (optional)</div><div class="param-desc"><span class="param-type"><a href="#boolean">Boolean</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: false</span></div>
<div class="param">deletedAt (optional)</div><div class="param-desc"><span class="param-type"><a href="#DateTime">Date</a></span>  format: date-time</div>
          <div class="param-desc"><span class="param-type">example: 2020-06-30T10:00-03:00</span></div>
<div class="param">_links (optional)</div><div class="param-desc"><span class="param-type"><a href="#City__links">City__links</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="City__links"><code>City__links</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">self (optional)</div><div class="param-desc"><span class="param-type"><a href="#City__links_self">City__links_self</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="City__links_self"><code>City__links_self</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">href (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: http://localhost:8080/v1/city/90f10584-6260-4d99-a23d-f521934b865f</span></div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="CollectionCity"><code>CollectionCity</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">_total_items (optional)</div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
<div class="param">_page (optional)</div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
<div class="param">_page_count (optional)</div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
<div class="param">_links (optional)</div><div class="param-desc"><span class="param-type"><a href="#CollectionState__links">CollectionState__links</a></span>  </div>
<div class="param">_embedded (optional)</div><div class="param-desc"><span class="param-type"><a href="#CollectionCity__embedded">CollectionCity__embedded</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="CollectionCity__embedded"><code>CollectionCity__embedded</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">states (optional)</div><div class="param-desc"><span class="param-type"><a href="#City">array[City]</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="CollectionState"><code>CollectionState</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">_total_items (optional)</div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
<div class="param">_page (optional)</div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
<div class="param">_page_count (optional)</div><div class="param-desc"><span class="param-type"><a href="#integer">Integer</a></span>  format: int32</div>
<div class="param">_links (optional)</div><div class="param-desc"><span class="param-type"><a href="#CollectionState__links">CollectionState__links</a></span>  </div>
<div class="param">_embedded (optional)</div><div class="param-desc"><span class="param-type"><a href="#CollectionState__embedded">CollectionState__embedded</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="CollectionState__embedded"><code>CollectionState__embedded</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">states (optional)</div><div class="param-desc"><span class="param-type"><a href="#State">array[State]</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="CollectionState__links"><code>CollectionState__links</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">self (optional)</div><div class="param-desc"><span class="param-type"><a href="#CollectionState__links_self">CollectionState__links_self</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="CollectionState__links_self"><code>CollectionState__links_self</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">href (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: http://{{host}}/v1/state?page&#x3D;1</span></div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="State"><code>State</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">id (optional)</div><div class="param-desc"><span class="param-type"><a href="#UUID">UUID</a></span>  format: uuid</div>
          <div class="param-desc"><span class="param-type">example: 90f0fd07-f3c4-42a1-84fe-b29fa1af04da</span></div>
<div class="param">name (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  format: string</div>
          <div class="param-desc"><span class="param-type">example: Rio de Janeiro</span></div>
<div class="param">shortName (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  format: string</div>
          <div class="param-desc"><span class="param-type">example: RJ</span></div>
<div class="param">createdAt (optional)</div><div class="param-desc"><span class="param-type"><a href="#DateTime">Date</a></span>  format: date-time</div>
          <div class="param-desc"><span class="param-type">example: 2020-06-30T10:00-03:00</span></div>
<div class="param">updatedAt (optional)</div><div class="param-desc"><span class="param-type"><a href="#DateTime">Date</a></span>  format: date-time</div>
          <div class="param-desc"><span class="param-type">example: 2020-06-30T10:00-03:00</span></div>
<div class="param">deleted (optional)</div><div class="param-desc"><span class="param-type"><a href="#boolean">Boolean</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: false</span></div>
<div class="param">deletedAt (optional)</div><div class="param-desc"><span class="param-type"><a href="#DateTime">Date</a></span>  format: date-time</div>
          <div class="param-desc"><span class="param-type">example: 2020-06-30T10:00-03:00</span></div>
<div class="param">_links (optional)</div><div class="param-desc"><span class="param-type"><a href="#State__links">State__links</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="State__links"><code>State__links</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">self (optional)</div><div class="param-desc"><span class="param-type"><a href="#State__links_self">State__links_self</a></span>  </div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="State__links_self"><code>State__links_self</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">href (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: http://localhost:8080/v1/state/90f0fd07-f3c4-42a1-84fe-b29fa1af04da</span></div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="body"><code>body</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">name (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: Rio de Janeiro</span></div>
<div class="param">uf (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: RJ</span></div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="body_1"><code>body_1</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">name (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: Rio de Janeiro</span></div>
<div class="param">uf (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: RJ</span></div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="body_2"><code>body_2</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">name (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: Rio de Janeiro</span></div>
<div class="param">stateId (optional)</div><div class="param-desc"><span class="param-type"><a href="#UUID">UUID</a></span>  format: uuid</div>
          <div class="param-desc"><span class="param-type">example: 90f108b0-f499-4619-8acc-87f35d4b3062</span></div>
    </div>  <!-- field-items -->
  </div>
  <div class="model">
    <h3><a name="body_3"><code>body_3</code></a> <a class="up" href="#__Models">Up</a></h3>

    <div class="field-items">
      <div class="param">name (optional)</div><div class="param-desc"><span class="param-type"><a href="#string">String</a></span>  </div>
          <div class="param-desc"><span class="param-type">example: Rio de Janeiro</span></div>
<div class="param">stateId (optional)</div><div class="param-desc"><span class="param-type"><a href="#UUID">UUID</a></span>  format: uuid</div>
          <div class="param-desc"><span class="param-type">example: 90f0fd07-f3c4-42a1-84fe-b29fa1af04da</span></div>
    </div>  <!-- field-items -->
  </div>
  </body>
</html>
