version: '3'

services:
  api-php:
    image: zooxsmart/php:7.4-fpm
    container_name: api-php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
      - ./docker/php/php-development.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-custom.conf

  api:
    image: nginx:latest
    container_name: api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: mongo:3.4
    container_name: mongo
    volumes:
      - ./docker/data/mongo:/data/db:rw
    ports:
      - "27017:27017"
